---
- hosts: localhost
  gather_facts: no

  vars_prompt:

  - name: vcenter_username
    prompt: Enter the vcenter username
    private: no

  - name: vcenter_password
    prompt: Enter the vcenter password
    private: yes

  - name: vm_name
    prompt: Enter the VM name, use the naming convention
    private: no

  - name: port_group
    prompt: Please specify the port group (either VLAN 10 - Secure LAN or VLAN 20 - DMZ)
    private: no

  - name: vm_ip
    prompt: Enter the IP address for the VM
    private: no

  - name: gateway
    prompt: Please specify the gateway according to the specified port group
    private: no



  tasks:

  - set_fact: 
      vm_name: "{{ vm_name }}"
  - set_fact:
      vm_ip: "{{ vm_ip }}"

  - name: Clone the template
    vmware_guest:
      hostname: "192.168.1.3"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: ubuntu18
      datacenter: "ESXi laboppl"
      folder: /"{{ port_group }}"
      datastore: "laboppl1"
      networks:
      - name: "{{ port_group }}"
        ip: "{{ vm_ip }}"
        netmask: 255.255.255.0
        gateway: "{{ gateway }}"
        type: static
        mac: "{{ '00:50:06' | random_mac }}"
      customization:
        hostname: "{{ vm_name | regex_search('^[^\\s]+') }}"
        dns_servers:
          - 10.0.10.1
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost


